name: Newman API Tests

on:
  push:
    branches:
      - main  # Workflow ini akan dijalankan saat kamu push ke branch 'main'
  pull_request:
    branches:
      - main  # Workflow ini akan dijalankan saat ada pull request ke branch 'main'
  workflow_dispatch:  # Menambahkan opsi untuk menjalankan workflow secara manual

jobs:
  newman-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Newman
        run: |
          npm install -g newman

      - name: Run Newman tests
        run: |
          newman run tests/NewmanDemo.postman_collection.json -e tests/ReqResdev.postman_environtment.json
